// lib/games/Quiz_Game/questions_data.dart

import 'question_model.dart';
import 'ModeSelectorPage.dart'; // for QuizLanguage enum

final Map<QuizLanguage, List<Question>> questionsByLanguage = {
  QuizLanguage.english: [
    Question('🌤️ What color is the sky?', ['Blue', 'Green', 'Red', 'Yellow'], 0),
    Question('🕷️ How many legs does a spider have?', ['6', '8', '10', '4'], 1),
    Question('🐶 Which animal barks?', ['Cat', 'Cow', 'Dog', 'Bird'], 2),
    Question('🧮 What is 2 + 2?', ['3', '4', '5'], 1),
    Question('🍌 Which one is a fruit?', ['Carrot', 'Banana', 'Potato', 'Onion'], 1),
    Question('🐶 Which one is an animal?', ['Car', 'Dog', 'Table', 'Chair'], 1),
    Question('🌈 What color is the sky?', ['Green', 'Blue', 'Red', 'Yellow'], 1),
    Question('🚗 Which one can fly?', ['Car', 'Boat', 'Airplane', 'Bike'], 2),
    Question('🍎 Which one is red?', ['Banana', 'Apple', 'Grape', 'Orange'], 1),
    Question('🌻 Which one is a flower?', ['Rose', 'Tree', 'Grass', 'Rock'], 0),
    Question('🐸 Which one lives in water?', ['Dog', 'Frog', 'Cat', 'Horse'], 1),
    Question('🍪 Which one is a sweet treat?', ['Bread', 'Cookie', 'Rice', 'Potato'], 1),
    Question('🎵 Which one is a musical instrument?', ['Piano', 'Book', 'Chair', 'Pen'], 0),
    Question('⚽ What do you use to play soccer?', ['Ball', 'Bat', 'Glove', 'Racket'], 0),
    Question('🌟 Which one shines in the night sky?', ['Moon', 'Sun', 'Cloud', 'Tree'], 0),
    Question('🐱 Which animal says "meow"?', ['Dog', 'Cat', 'Cow', 'Bird'], 1),
    Question('🌽 Which one is a vegetable?', ['Corn', 'Apple', 'Banana', 'Orange'], 0),
    Question('🚗 Which one has four wheels?', ['Bike', 'Car', 'Plane', 'Boat'], 1),
    Question('🦋 What insect has colorful wings?', ['Ant', 'Fly', 'Butterfly', 'Bee'], 2),
    Question('🥚 What comes from a chicken?', ['Milk', 'Egg', 'Bread', 'Honey'], 1),
    Question('🌧️ What falls from clouds?', ['Sunlight', 'Rain', 'Snow', 'Wind'], 1),
    Question('🎈 What do you use at a birthday party?', ['Balloon', 'Shoe', 'Book', 'Pen'], 0),
    Question('🦁 Which animal is called the "king of the jungle"?', ['Tiger', 'Lion', 'Elephant', 'Bear'], 1),
    Question('🍓 What color is a strawberry?', ['Blue', 'Red', 'Yellow', 'Green'], 1),
    Question('🐦 What animal can fly?', ['Dog', 'Cat', 'Bird', 'Fish'], 2),
    Question('🍕 What food has cheese?', ['Pizza', 'Burger', 'Pasta', 'Soup'], 0),
    Question('🌙 What do you see in the night sky?', ['Sun', 'Moon', 'Tree', 'Car'], 1),
    Question('🧸 What toy can you hug?', ['Ball', 'Doll', 'Teddy Bear', 'Car'], 2),
    Question('🐠 Which one lives in water?', ['Dog', 'Fish', 'Cat', 'Horse'], 1),
    Question('📅 How many days are in a week?', ['5', '6', '7', '8'], 2),
    Question('🌹 Which one is a flower?', ['Tree', 'Grass', 'Rose', 'Rock'], 2),
    Question('🍰 What do you eat on your birthday?', ['Cake', 'Pizza', 'Soup', 'Salad'], 0),
    Question('🚌 What do you take to go to school?', ['Car', 'Bus', 'Bike', 'Plane'], 1),
    Question('🎤 What do singers use?', ['Microphone', 'Book', 'Pen', 'Phone'], 0),
    Question('🐴 Which animal can you ride?', ['Dog', 'Horse', 'Cat', 'Bird'], 1),
    Question('🌞 What is bright and hot?', ['Sun', 'Moon', 'Star', 'Cloud'], 0),
    Question('📏 What do you use to measure?', ['Pen', 'Ruler', 'Book', 'Paper'], 1),
    Question('🍎 What color is an apple?', ['Green', 'Red', 'Blue', 'Yellow'], 1),
    Question('🚢 What floats on water?', ['Car', 'Boat', 'Bike', 'Plane'], 1),
    Question('🐧 Where do penguins live?', ['Desert', 'Arctic', 'Antarctica', 'Jungle'], 2),
    Question('🍫 What is sweet and made of cocoa?', ['Candy', 'Chocolate', 'Bread', 'Cheese'], 1),
    Question('🌲 What type of plant is tall and has needles?', ['Tree', 'Flower', 'Grass', 'Bush'], 0),
    Question('🎮 What do you use to play video games?', ['Controller', 'Book', 'Pen', 'Phone'], 0),
    Question('🕰️ What tells you the time?', ['Clock', 'Phone', 'Book', 'Chair'], 0),
    Question('🌂 What do you use when it rains?', ['Hat', 'Umbrella', 'Coat', 'Sunglasses'], 1),



    // ... add the rest of English questions here
  ],
  QuizLanguage.french: [
    Question('🌤️ Quelle est la couleur du ciel ?', ['Bleu', 'Vert', 'Rouge', 'Jaune'], 0),
    Question('🕷️ Combien de pattes a une araignée ?', ['6', '8', '10', '4'], 1),
    Question('🐶 Quel animal aboie ?', ['Chat', 'Vache', 'Chien', 'Oiseau'], 2),
    Question('🧮 Combien font 2 + 2 ?', ['3', '4', '5'], 1),
    Question('🍌 Lequel est un fruit ?', ['Carotte', 'Banane', 'Pomme de terre', 'Oignon'], 1),
    Question('🐶 Lequel est un animal ?', ['Voiture', 'Chien', 'Table', 'Chaise'], 1),
    Question('🌈 Quelle est la couleur du ciel ?', ['Vert', 'Bleu', 'Rouge', 'Jaune'], 1),
    Question('🚗 Lequel peut voler ?', ['Voiture', 'Bateau', 'Avion', 'Vélo'], 2),
    Question('🍎 Lequel est rouge ?', ['Banane', 'Pomme', 'Raisin', 'Orange'], 1),
    Question('🌻 Lequel est une fleur ?', ['Rose', 'Arbre', 'Herbe', 'Roche'], 0),
    Question('🐸 Lequel vit dans l’eau ?', ['Chien', 'Grenouille', 'Chat', 'Cheval'], 1),
    Question('🍪 Lequel est une douceur ?', ['Pain', 'Cookie', 'Riz', 'Pomme de terre'], 1),
    Question('🎵 Lequel est un instrument de musique ?', ['Piano', 'Livre', 'Chaise', 'Stylo'], 0),
    Question('⚽ Qu’utilisez-vous pour jouer au football ?', ['Balle', 'Batte', 'Gant', 'Raquette'], 0),
    Question('🌟 Lequel brille dans le ciel nocturne ?', ['Lune', 'Soleil', 'Nuage', 'Arbre'], 0),
    // ... add the rest of French questions here
  ],
  QuizLanguage.arabic: [
    Question('🌤️ ما لون السماء؟', ['أزرق', 'أخضر', 'أحمر', 'أصفر'], 0),
    Question('🕷️ كم عدد أرجل العنكبوت؟', ['6', '8', '10', '4'], 1),
    Question('🐶 أي حيوان ينبح؟', ['قط', 'بقرة', 'كلب', 'عصفور'], 2),
    Question('🧮 كم يساوي 2 + 2؟', ['3', '4', '5'], 1),
    Question('🍌 أيهم فاكهة؟', ['جزرة', 'موز', 'بطاطا', 'بصل'], 1),
    Question('🐶 أيهم حيوان؟', ['سيارة', 'كلب', 'طاولة', 'كرسي'], 1),
    Question('🌈 ما لون السماء؟', ['أخضر', 'أزرق', 'أحمر', 'أصفر'], 1),
    Question('🚗 أيهم يستطيع الطيران؟', ['سيارة', 'قارب', 'طائرة', 'دراجة'], 2),
    Question('🍎 أيهما أحمر؟', ['موز', 'تفاح', 'عنب', 'برتقال'], 1),
    Question('🌻 أيهما زهرة؟', ['وردة', 'شجرة', 'عشب', 'صخرة'], 0),
    Question('🐸 أيهما يعيش في الماء؟', ['كلب', 'ضفدع', 'قط', 'حصان'], 1),
    Question('🍪 أيهما حلوى؟', ['خبز', 'كوكي', 'أرز', 'بطاطا'], 1),
    Question('🎵 أيهما آلة موسيقية؟', ['بيانو', 'كتاب', 'كرسي', 'قلم'], 0),
    Question('⚽ ماذا تستخدم للعب كرة القدم؟', ['كرة', 'مضرب', 'قفاز', 'مضرب تنس'], 0),
    Question('🌟 أيهما يلمع في السماء ليلاً؟', ['قمر', 'شمس', 'سحاب', 'شجرة'], 0),
    // ... add the rest of Arabic questions here
  ],
};
