
import 'question_model.dart';
import 'ModeSelectorPage.dart'; // for QuizLanguage enum


List<Question> getQuestionsForLanguage(QuizLanguage lang) {
  final originalQuestions = questionsByLanguage[lang] ?? [];
  return originalQuestions.map((q) => q.shuffled()).toList();
}


final Map<QuizLanguage, List<Question>> questionsByLanguage = {


  QuizLanguage.english: [
    Question(1, 'What color is the sky?', ['Green', 'Blue', 'Red', 'Yellow'], 1),
    Question(2, 'How many legs does a spider have?', ['6', '10', '8', '4'], 2),
    Question(3, 'Which animal barks?', ['Cat', 'Cow', 'Bird', 'Dog'], 3),
    Question(4, 'What is 2 + 2?', ['4', '3', '5'], 0),
    Question(5, 'Which one is a fruit?', ['Banana', 'Potato', 'Onion', 'Carrot'], 0),
    Question(6, 'Which one is an animal?', ['Table', 'Dog', 'Chair', 'Car'], 1),
    Question(7, 'What color is the grass?', ['Red', 'Yellow', 'Green', 'Blue'], 2),
    Question(8, 'Which one can fly?', ['Airplane', 'Boat', 'Car', 'Bike'], 0),
    Question(9, 'Which one is red?', ['Banana', 'Orange', 'Apple', 'Grape'], 2),
    Question(10, 'Which one is a flower?', ['Rock', 'Grass', 'Tree', 'Rose'], 3),
    Question(11, 'Which one lives in water?', ['Cat', 'Frog', 'Horse', 'Dog'], 1),
    Question(12, 'Which one is a sweet treat?', ['Cookie', 'Bread', 'Rice', 'Potato'], 0),
    Question(13, 'Which one is a musical instrument?', ['Book', 'Piano', 'Pen', 'Chair'], 1),
    Question(14, 'What do you use to play soccer?', ['Bat', 'Ball', 'Racket', 'Glove'], 1),
    Question(15, 'Which one shines in the night sky?', ['Cloud', 'Tree', 'Moon', 'Sun'], 2),
    Question(16, 'Which animal says "meow"?', ['Dog', 'Cat', 'Bird', 'Cow'], 1),
    Question(17, 'Which one is a vegetable?', ['Apple', 'Corn', 'Banana', 'Orange'], 1),
    Question(18, 'Which one has four wheels?', ['Car', 'Bike', 'Boat', 'Plane'], 0),
    Question(19, 'What insect has colorful wings?', ['Ant', 'Butterfly', 'Bee', 'Fly'], 1),
    Question(20, 'What comes from a chicken?', ['Bread', 'Honey', 'Egg', 'Milk'], 2),
    Question(21, 'What falls from clouds?', ['Rain', 'Snow', 'Sunlight', 'Wind'], 0),
    Question(22, 'What do you use at a birthday party?', ['Book', 'Balloon', 'Shoe', 'Pen'], 1),
    Question(23, 'Which animal is called the "king of the jungle"?', ['Lion', 'Tiger', 'Elephant', 'Bear'], 0),
    Question(24, 'What color is a strawberry?', ['Yellow', 'Red', 'Blue', 'Green'], 1),
    Question(25, 'What animal can fly?', ['Cat', 'Bird', 'Dog', 'Fish'], 1),
    Question(26, 'What food has cheese?', ['Soup', 'Burger', 'Pizza', 'Pasta'], 2),
    Question(27, 'What do you see in the night sky?', ['Tree', 'Moon', 'Sun', 'Car'], 1),
    Question(28, 'What toy can you hug?', ['Teddy Bear', 'Doll', 'Car', 'Ball'], 0),
    Question(29, 'Which one lives in water?', ['Horse', 'Fish', 'Dog', 'Cat'], 1),
    Question(30, 'How many days are in a week?', ['8', '6', '7', '5'], 2),
    Question(31, 'Which one is a flower?', ['Rose', 'Tree', 'Grass', 'Rock'], 0),
    Question(32, 'What do you eat on your birthday?', ['Soup', 'Cake', 'Salad', 'Pizza'], 1),
    Question(33, 'What do you take to go to school?', ['Bus', 'Car', 'Plane', 'Bike'], 0),
    Question(34, 'What do singers use?', ['Pen', 'Microphone', 'Book', 'Phone'], 1),
    Question(35, 'Which animal can you ride?', ['Bird', 'Horse', 'Cat', 'Dog'], 1),
    Question(36, 'What is bright and hot?', ['Star', 'Moon', 'Sun', 'Cloud'], 2),
    Question(37, 'What do you use to measure?', ['Book', 'Pen', 'Ruler', 'Paper'], 2),
    Question(38, 'What color is an apple?', ['Blue', 'Green', 'Yellow', 'Red'], 3),
    Question(39, 'What floats on water?', ['Bike', 'Boat', 'Plane', 'Car'], 1),
    Question(40, 'Where do penguins live?', ['Arctic', 'Antarctica', 'Jungle', 'Desert'], 1),
    Question(41, 'What is sweet and made of cocoa?', ['Chocolate', 'Cheese', 'Bread', 'Candy'], 0),
    Question(42, 'What type of plant is tall and has needles?', ['Grass', 'Tree', 'Bush', 'Flower'], 1),
    Question(43, 'What do you use to play video games?', ['Controller', 'Book', 'Phone', 'Pen'], 0),
    Question(44, 'What tells you the time?', ['Book', 'Chair', 'Clock', 'Phone'], 2),
    Question(45, 'What do you use when it rains?', ['Umbrella', 'Hat', 'Sunglasses', 'Coat'], 0),
  ],

  QuizLanguage.french: [
    Question(1, 'Quelle est la couleur du ciel ?', ['Vert', 'Bleu', 'Rouge', 'Jaune'], 1),
    Question(2, 'Combien de pattes a une araignée ?', ['6', '10', '8', '4'], 2),
    Question(3, 'Quel animal aboie ?', ['Chat', 'Vache', 'Oiseau', 'Chien'], 3),
    Question(4, 'Combien font 2 + 2 ?', ['4', '3', '5'], 0),
    Question(5, 'Lequel est un fruit ?', ['Carotte', 'Pomme de terre', 'Banane', 'Oignon'], 2),
    Question(6, 'Lequel est un animal ?', ['Voiture', 'Chien', 'Chaise', 'Table'], 1),
    Question(7, 'Quelle est la couleur de l’herbe ?', ['Rouge', 'Jaune', 'Vert', 'Bleu'], 2),
    Question(8, 'Lequel peut voler ?', ['Bateau', 'Avion', 'Voiture', 'Vélo'], 1),
    Question(9, 'Lequel est rouge ?', ['Pomme', 'Banane', 'Raisin', 'Orange'], 0),
    Question(10, 'Lequel est une fleur ?', ['Herbe', 'Roche', 'Rose', 'Arbre'], 2),
    Question(11, 'Lequel vit dans l’eau ?', ['Cheval', 'Grenouille', 'Chat', 'Chien'], 1),
    Question(12, 'Lequel est une douceur ?', ['Cookie', 'Pain', 'Riz', 'Pomme de terre'], 0),
    Question(13, 'Lequel est un instrument de musique ?', ['Piano', 'Livre', 'Chaise', 'Stylo'], 0),
    Question(14, 'Qu’utilisez-vous pour jouer au football ?', ['Raquette', 'Balle', 'Batte', 'Gant'], 1),
    Question(15, 'Lequel brille dans le ciel nocturne ?', ['Nuage', 'Soleil', 'Lune', 'Arbre'], 2),

    // Nouvelles questions :
    Question(16, 'Quel est le roi des animaux ?', ['Lion', 'Tigre', 'Éléphant', 'Ours'], 0),
    Question(17, 'Lequel est un fruit d’été ?', ['Pastèque', 'Citrouille', 'Carotte', 'Pomme'], 0),
    Question(18, 'Quelle planète habitons-nous ?', ['Mars', 'Terre', 'Venus', 'Jupiter'], 1),
    Question(19, 'Quel véhicule va dans l’espace ?', ['Fusée', 'Avion', 'Bateau', 'Voiture'], 0),
    Question(20, 'Où lit-on des livres ?', ['Piscine', 'Bibliothèque', 'Garage', 'Restaurant'], 1),
    Question(21, 'Quel animal peut voler ?', ['Poisson', 'Oiseau', 'Chien', 'Serpent'], 1),
    Question(22, 'Que tombe du ciel quand il pleut ?', ['Vent', 'Neige', 'Sable', 'Pluie'], 3),
    Question(23, 'Que trouve-t-on dans un nid ?', ['Œufs', 'Nourriture', 'Feuilles', 'Pierres'], 0),
    Question(24, 'Quel aliment est sucré ?', ['Tomate', 'Chocolat', 'Fromage', 'Pain'], 1),
    Question(25, 'Que montre une horloge ?', ['La vitesse', 'Le temps', 'La distance', 'La température'], 1),
    Question(26, 'Où vit une famille ?', ['Maison', 'Magasin', 'École', 'Hôpital'], 0),
    Question(27, 'Où vit un poisson ?', ['Air', 'Feu', 'Eau', 'Terre'], 2),
    Question(28, 'Quel objet utilise un peintre ?', ['Couteau', 'Pinceau', 'Clé', 'Livre'], 1),
    Question(29, 'Quel moyen de transport a deux roues ?', ['Voiture', 'Avion', 'Bateau', 'Vélo'], 3),
    Question(30, 'Que célèbre-t-on avec un gâteau ?', ['Halloween', 'Anniversaire', 'Noël', 'Pâques'], 1),
    Question(31, 'Quel est un arbre commun ?', ['Tulipe', 'Pin', 'Marguerite', 'Rose'], 1),
    Question(32, 'Quel insecte produit du miel ?', ['Papillon', 'Fourmi', 'Abeille', 'Mouche'], 2),
    Question(33, 'Que trouve-t-on en hiver ?', ['Pluie', 'Soleil', 'Feuilles', 'Neige'], 3),
    Question(34, 'Quel objet sert à téléphoner ?', ['Téléphone', 'Ordinateur', 'Radio', 'Télévision'], 0),
    Question(35, 'Quel véhicule sert à éteindre le feu ?', ['Ambulance', 'Camion de pompiers', 'Voiture', 'Camion'], 1),
    Question(36, 'Quel animal est un rongeur ?', ['Chien', 'Lapin', 'Chat', 'Poisson'], 1),
    Question(37, 'Quel aliment vient du blé ?', ['Pain', 'Viande', 'Fromage', 'Fruits'], 0),
    Question(38, 'Que porte-t-on pour mieux voir ?', ['Lunettes', 'Chaussures', 'Casquette', 'Montre'], 0),
    Question(39, 'Où dort-on ?', ['Lit', 'Table', 'Chaise', 'Canapé'], 0),
    Question(40, 'Quel animal a un long cou ?', ['Girafe', 'Zèbre', 'Lion', 'Éléphant'], 0),
    Question(41, 'Que fait un chanteur ?', ['Peindre', 'Chanter', 'Danser', 'Cuisiner'], 1),
    Question(42, 'Où voit-on des films ?', ['Cinéma', 'Bibliothèque', 'École', 'Hôpital'], 0),
    Question(43, 'Où va-t-on pour se baigner ?', ['Forêt', 'Plage', 'Montagne', 'Désert'], 1),
  ],



  QuizLanguage.arabic: [
    Question(1, 'ما لون السماء؟', ['أزرق', 'أخضر', 'أحمر', 'أصفر'], 0),
    Question(2, 'كم عدد أرجل العنكبوت؟', ['6', '10', '8', '4'], 2),
    Question(3, 'أي حيوان ينبح؟', ['قط', 'بقرة', 'عصفور', 'كلب'], 3),
    Question(4, 'كم يساوي 2 + 2؟', ['4', '3', '5'], 0),
    Question(5, 'أيهم فاكهة؟', ['جزرة', 'بطاطا', 'موز', 'بصل'], 2),
    Question(6, 'أيهم حيوان؟', ['سيارة', 'كرسي', 'كلب', 'طاولة'], 2),
    Question(7, 'ما لون العشب؟', ['أخضر', 'أحمر', 'أزرق', 'أصفر'], 0),
    Question(8, 'أيهم يستطيع الطيران؟', ['دراجة', 'قارب', 'طائرة', 'سيارة'], 2),
    Question(9, 'أيهما أحمر؟', ['برتقال', 'تفاح', 'عنب', 'موز'], 1),
    Question(10, 'أيهما زهرة؟', ['شجرة', 'وردة', 'عشب', 'صخرة'], 1),
    Question(11, 'أيهما يعيش في الماء؟', ['كلب', 'قط', 'ضفدع', 'حصان'], 2),
    Question(12, 'أيهما حلوى؟', ['كوكي', 'خبز', 'أرز', 'بطاطا'], 0),
    Question(13, 'أيهما آلة موسيقية؟', ['كتاب', 'بيانو', 'كرسي', 'قلم'], 1),
    Question(14, 'ماذا تستخدم للعب كرة القدم؟', ['قفاز', 'مضرب', 'كرة', 'مضرب تنس'], 2),
    Question(15, 'أيهما يلمع في السماء ليلاً؟', ['قمر', 'شمس', 'سحاب', 'شجرة'], 0),
    Question(16, 'كم عدد أصابع اليد الواحدة؟', ['7', '6', '4', '5'], 3),
    Question(17, 'ما هو الحيوان الذي يقول "مياو"؟', ['قطة', 'كلب', 'حصان', 'بقرة'], 0),
    Question(18, 'أي منهم يستخدم للشرب؟', ['قلم', 'كرسي', 'كوب', 'كتاب'], 2),
    Question(19, 'أي حيوان يعيش في البحر؟', ['حصان', 'سمكة', 'قط', 'كلب'], 1),
    Question(20, 'ما هو لون الموز؟', ['أصفر', 'أخضر', 'أحمر', 'أزرق'], 0),
    Question(21, 'أي طعام مصنوع من الدقيق؟', ['لحم', 'تفاح', 'خبز', 'بيض'], 2),
    Question(22, 'أين يذهب الأطفال للتعلم؟', ['مزرعة', 'مدرسة', 'مطعم', 'سوق'], 1),
    Question(23, 'كم عدد الأرجل للحصان؟', ['4', '8', '2', '6'], 0),
    Question(24, 'ما هي الفاكهة الخضراء؟', ['فراولة', 'عنب', 'جزر', 'تفاح'], 1),
    Question(25, 'ما الذي نستخدمه للنوم؟', ['سرير', 'كرسي', 'كتاب', 'طاولة'], 0),
    Question(26, 'أيهما وسيلة نقل؟', ['كلب', 'سيارة', 'حقيبة', 'شجرة'], 1),
    Question(27, 'ما الذي نراه في الليل؟', ['قمر', 'زهرة', 'قوس قزح', 'شمس'], 0),
    Question(28, 'أي حيوان يبيض؟', ['دجاجة', 'قطة', 'كلب', 'حصان'], 0),
    Question(29, 'أين نذهب لشراء الطعام؟', ['ملعب', 'مستشفى', 'سوبرماركت', 'مدرسة'], 2),
    Question(30, 'كم عدد أيام الأسبوع؟', ['8', '7', '5', '6'], 1),
    Question(31, 'ما الذي نستخدمه للكتابة؟', ['طبق', 'قلم', 'كرسي', 'زجاجة'], 1),
    Question(32, 'ما لون الحليب؟', ['أزرق', 'أبيض', 'أخضر', 'أحمر'], 1),
    Question(33, 'أيهما خضار؟', ['فراولة', 'موز', 'بطاطا', 'تفاح'], 2),
    Question(34, 'أيهما نأكله في الصيف؟', ['بيتزا', 'شوربة', 'آيس كريم', 'خبز'], 2),
    Question(35, 'أي كوكب نعيش عليه؟', ['المريخ', 'القمر', 'الأرض', 'الشمس'], 2),
    Question(36, 'أي شيء نستخدمه عند المطر؟', ['كرسي', 'مظلة', 'كتاب', 'حقيبة'], 1),
    Question(37, 'ما الحيوان الذي لديه خرطوم؟', ['كلب', 'حصان', 'فيل', 'قطة'], 2),
    Question(38, 'ما الحيوان الذي يصنع العسل؟', ['قطة', 'نحلة', 'بقرة', 'كلب'], 1),
    Question(39, 'كم عدد الدقائق في الساعة؟', ['90', '30', '60', '120'], 2),
    Question(40, 'ما هو الشيء الذي نأكله؟', ['كتاب', 'قلم', 'كرسي', 'تفاح'], 3),
    Question(41, 'أي حيوان له جناحان؟', ['عصفور', 'قطة', 'كلب', 'حصان'], 0),
    Question(42, 'ما الذي نستخدمه للاستحمام؟', ['صابون', 'كرسي', 'قلم', 'كتاب'], 0),
    Question(43, 'كم عدد الفصول في السنة؟', ['4', '2', '5', '3'], 0),
    Question(44, 'أيهما حار؟', ['ثلج', 'شمس', 'حليب', 'ماء بارد'], 1),

  ],




  QuizLanguage.deutch: [
    Question(1, 'Welche Farbe hat ein typisches Polizeiauto in Deutschland?', ['Blau', 'Rot', 'Grün', 'Gelb'], 0),
    Question(2, 'Wie nennt man ein großes, altes Schloss?', ['Palast', 'Burg', 'Hütte', 'Haus'], 1),
    Question(3, 'Welches Fest feiern wir am 24. Dezember?', ['Ostern', 'Weihnachten', 'Pfingsten', 'Silvester'], 1),
    Question(4, 'Was wächst auf einem Bauernhof?', ['Weizen', 'Computer', 'Auto', 'Buch'], 0),
    Question(5, 'Was braucht man für eine Fahrradtour?', ['Helm', 'Anzug', 'Regenschirm', 'Schuhe'], 0),
    Question(6, 'Wie nennt man den Platz, wo viele Bäume wachsen?', ['Wald', 'Park', 'Strand', 'Berg'], 0),
    Question(7, 'Was ist eine berühmte deutsche Spezialität?', ['Pizza', 'Käse', 'Sushi', 'Tacos'], 1),
    Question(8, 'Wo lernen Kinder?', ['Haus', 'Schule', 'Supermarkt', 'Theater'], 1),
    Question(9, 'Wie viele Monate hat ein Jahr?', ['10', '12', '14', '8'], 1),
    Question(10, 'Was fährt auf Schienen?', ['Auto', 'Fahrrad', 'Zug', 'Boot'], 2),
    Question(11, 'Was kann man essen?', ['Stein', 'Apfel', 'Stuhl', 'Buch'], 1),
    Question(12, 'Wann ist es meistens warm?', ['Winter', 'Sommer', 'Herbst', 'Frühling'], 1),
    Question(13, 'Wie nennt man eine Zeitspanne von 60 Minuten?', ['Tag', 'Stunde', 'Sekunde', 'Woche'], 1),
    Question(14, 'Wo wohnt man?', ['Haus', 'Laden', 'Park', 'Kino'], 0),
    Question(15, 'Wo kauft man Lebensmittel?', ['Bibliothek', 'Supermarkt', 'Schule', 'Tankstelle'], 1),
    Question(16, 'Was kann man reiten?', ['Pferd', 'Auto', 'Fahrrad', 'Boot'], 0),
    Question(17, 'Welches Essen ist typisch französisch?', ['Baguette', 'Sushi', 'Pizza', 'Burger'], 0),
    Question(18, 'Was schaut man im Fernsehen?', ['Buch', 'Film', 'Stuhl', 'Radio'], 1),
    Question(19, 'Was braucht man für Strom?', ['Kabel', 'Wasser', 'Holz', 'Sand'], 0),
    Question(20, 'Welches Fahrzeug fliegt am Himmel?', ['Auto', 'Schiff', 'Flugzeug', 'Fahrrad'], 2),
    Question(21, 'Welche Blume ist ein Symbol der Liebe?', ['Rose', 'Tulpe', 'Lilie', 'Sonnenblume'], 0),
    Question(22, 'Was isst man im Sommer gerne?', ['Eis', 'Kuchen', 'Suppe', 'Brot'], 0),
    Question(23, 'Wie heißt der Himmelskörper, der nachts leuchtet?', ['Sonne', 'Mond', 'Stern', 'Wolke'], 1),
    Question(24, 'Wofür benutzt man eine Dusche?', ['Waschen', 'Kochen', 'Schlafen', 'Lesen'], 0),
    Question(25, 'Was macht man mit einem Buch?', ['Lesen', 'Schreiben', 'Kochen', 'Malen'], 0),
    Question(26, 'Was gibt man zu Geburtstagen?', ['Geschenk', 'Stuhl', 'Lampe', 'Teller'], 0),
    Question(27, 'Welches Tier ist ein Haustier?', ['Hund', 'Löwe', 'Tiger', 'Elefant'], 0),
    Question(28, 'Wie viele Farben hat ein Regenbogen?', ['5', '7', '9', '11'], 1),
    Question(29, 'Was isst man zu einer Feier?', ['Kuchen', 'Reis', 'Salat', 'Fleisch'], 0),
  ],



  QuizLanguage.spanish: [
    Question(1, '¿Qué brilla durante el día?', ['Luna', 'Sol', 'Estrella', 'Nube'], 1),
    Question(2, '¿Cuántas patas tiene un gato?', ['2', '4', '6', '8'], 1),
    Question(3, '¿Qué animal pone huevos?', ['Vaca', 'Gallina', 'Perro', 'Caballo'], 1),
    Question(4, '¿Cuánto es 5 + 3?', ['7', '8', '9', '6'], 1),
    Question(5, '¿Cuál de estos es una fruta?', ['Papa', 'Naranja', 'Cebolla', 'Pan'], 1),
    Question(6, '¿Cuál de estos es un animal doméstico?', ['Perro', 'Mesa', 'Silla', 'Auto'], 0),
    Question(7, '¿Qué cubre la mayor parte de la Tierra?', ['Bosques', 'Océanos', 'Montañas', 'Ciudades'], 1),
    Question(8, '¿Qué puede volar?', ['Bicicleta', 'Avión', 'Tren', 'Coche'], 1),
    Question(9, '¿Qué fruta es morada?', ['Manzana', 'Uva', 'Plátano', 'Limón'], 1),
    Question(10, '¿Cuál es una flor?', ['Rosa', 'Roca', 'Hierba', 'Árbol'], 0),
    Question(11, '¿Qué animal tiene caparazón?', ['Tortuga', 'Rana', 'Perro', 'Pez'], 0),
    Question(12, '¿Qué producen las abejas?', ['Leche', 'Miel', 'Harina', 'Sal'], 1),
    Question(13, '¿Cuál es un instrumento musical?', ['Violín', 'Zapato', 'Libro', 'Cuchara'], 0),
    Question(14, '¿Qué se usa para jugar baloncesto?', ['Balón', 'Guante', 'Raqueta', 'Red'], 0),
    Question(15, '¿Qué ves en el cielo de noche?', ['Sol', 'Estrellas', 'Árboles', 'Montañas'], 1),
    Question(16, '¿Qué animal dice "muuu"?', ['Vaca', 'Gato', 'Perro', 'Pato'], 0),
    Question(17, '¿Cuál de estos es un vegetal?', ['Brócoli', 'Plátano', 'Fresa', 'Melón'], 0),
    Question(18, '¿Qué tiene dos ruedas?', ['Coche', 'Avión', 'Bicicleta', 'Barco'], 2),
    Question(19, '¿Qué insecto tiene alas de colores?', ['Mariposa', 'Hormiga', 'Mosquito', 'Abeja'], 0),
    Question(20, '¿Qué bebes con galletas?', ['Jugo', 'Leche', 'Café', 'Agua'], 1),
    Question(21, '¿Qué cae de las nubes?', ['Lluvia', 'Fuego', 'Arena', 'Rayo de sol'], 0),
    Question(22, '¿Qué llevas a una fiesta de cumpleaños?', ['Zapatos', 'Regalo', 'Silla', 'Taza'], 1),
    Question(23, '¿Qué animal tiene una cola grande y peluda?', ['León', 'Zorro', 'Elefante', 'Pato'], 1),
    Question(24, '¿De qué color son las cerezas?', ['Rojas', 'Azules', 'Verdes', 'Amarillas'], 0),
    Question(25, '¿Qué animal puede volar?', ['Ballena', 'Pájaro', 'Perro', 'Caballo'], 1),
    Question(26, '¿Qué comida se hace con harina?', ['Pizza', 'Pan', 'Ensalada', 'Carne'], 1),
    Question(27, '¿Qué ves en el cielo de noche además de estrellas?', ['Nubes', 'Luna', 'Árboles', 'Piedras'], 1),
    Question(28, '¿Qué juguete puedes abrazar?', ['Pelota', 'Oso de peluche', 'Auto', 'Lápiz'], 1),
    Question(29, '¿Qué animal vive en el agua?', ['Pez', 'Gato', 'Perro', 'León'], 0),
    Question(30, '¿Cuántos meses tiene un año?', ['10', '12', '11', '13'], 1),
    Question(31, '¿Qué planta tiene pétalos?', ['Rosa', 'Hierba', 'Cactus', 'Roca'], 0),
    Question(32, '¿Qué postre es frío?', ['Helado', 'Pizza', 'Pan', 'Carne'], 0),
    Question(33, '¿Qué usas para ir a la escuela?', ['Avión', 'Bicicleta', 'Autobús', 'Tren'], 2),
    Question(34, '¿Qué usas para escuchar música?', ['Audífonos', 'Libro', 'Plato', 'Reloj'], 0),
    Question(35, '¿Qué animal puedes montar?', ['Caballo', 'Pato', 'Pez', 'Gato'], 0),
    Question(36, '¿Qué es caliente?', ['Sol', 'Nieve', 'Hielo', 'Luna'], 0),
    Question(37, '¿Qué herramienta sirve para medir?', ['Regla', 'Cuchara', 'Lámpara', 'Zapato'], 0),
    Question(38, '¿Qué fruta es verde?', ['Manzana', 'Fresa', 'Sandía', 'Naranja'], 0),
    Question(39, '¿Qué se mueve en el agua?', ['Barco', 'Avión', 'Auto', 'Tren'], 0),
    Question(40, '¿Dónde viven los pingüinos?', ['Desierto', 'Antártida', 'Bosque', 'Montaña'], 1),
    Question(41, '¿Qué es un dulce?', ['Caramelo', 'Lechuga', 'Arroz', 'Pollo'], 0),
    Question(42, '¿Qué planta es alta y tiene tronco?', ['Árbol', 'Flor', 'Césped', 'Rosa'], 0),
    Question(43, '¿Qué usas para jugar videojuegos?', ['Control', 'Teléfono', 'Mesa', 'Cuaderno'], 0),
    Question(44, '¿Qué te dice la hora?', ['Reloj', 'Zapato', 'Papel', 'Puerta'], 0),
    Question(45, '¿Qué usas cuando llueve?', ['Sombrero', 'Paraguas', 'Bufanda', 'Sandalia'], 1),

  ],

QuizLanguage.amazigh: [
Question(1, 'ⴰⵎⴰⵏ ⴷⴰ ⵢⴻⵙⵏⵓⴼⴹ ⴰⵔ ⵜⴰⴷⴷⴰⵔⵜ?', ['ⴰⵎⴰⵏ', 'ⵜⴰⴼⴷⵓⵜ', 'ⵜⴰⵎⵜⵓⵜ', 'ⴰⵢⵢⵓⵔ'], 1),
Question(2, 'ⵎⴰⵏⵉ ⴰⵢⴻⵍⵍⴰ ⴷⴰ-ⴰⵎⴰⵏ ⵏ ⵡⴰⵎⴰⵏ?', ['ⵜⴰⵎⴷⵉⵏⵜ', 'ⴰⵎⴰⵏ', 'ⴰⵙⴼⵔⵓ', 'ⵜⴰⴷⴷⴰⵔⵜ'], 1),
Question(3, 'ⴰⵏⵡⴰ ⴰⵢⴻⵍⵍⴰ ⵢⴻⵙⵏⵓⴼⴹ ⵜⴰⵎⵖⴰⵔⵜ?', ['ⴰⵣⵏⵣⵓ', 'ⵜⵉⵎⵎⵓⵣ', 'ⴰⴼⵓⵙ', 'ⴰⵖⵔⵉⴱ'], 1),
Question(4, 'ⵎⴰ ⴰⵢⴻⵍⵍⴰ 5 + 3?', ['7', '8', '9', '6'], 1),
Question(5, 'ⵎⴰⵏⵉ ⴰⵢⴻⵍⵍⴰ ⴷ-ⴰⴼⵔⵓ ⵏ ⵜⵉⴽⵜⵉⵡⵉⵏ?', ['ⵜⵉⴽⵍⵉ', 'ⵜⴰⵎⵔ', 'ⵜⴰⴼⵓⴽ', 'ⴰⵢⴻⵏ'], 1),
Question(6, 'ⵎⴰⵏⵉ ⴰⵢⴻⵍⵍⴰ ⴷ-ⴰⵏⵉⵎⴰⵍ ⵏ ⵜⴰⴷⴷⴰⵔⵜ?', ['ⴰⵣⵏⵣⵓ', 'ⴰⴳⴰⴷⵉⵔ', 'ⴰⵙⵉⴼ', 'ⴰⵖⵔⵉⴱ'], 0),
Question(7, 'ⵎⴰⵏⵉ ⵢⴻⵙⵏⵓⴼⴹ ⴰⵔ ⵜⵎⵓⵔⵜ?', ['ⵜⴰⴼⵓⴽⵜ', 'ⴰⵎⴰⵏ', 'ⴰⴷⵔⴰⵔ', 'ⵜⴰⴷⴷⴰⵔⵜ'], 1),
Question(8, 'ⵎⴰⵏⵉ ⴰⵢⴻⵍⵍⴰ ⴷ-ⴰⵢⴰⴹ ⴰⴷ ⵢⴻⵙⵏⴰⴼⴻⵏ?', ['ⴰⵣⴰⵍ', 'ⵜⴰⵎⴷⴷⵉⵜ', 'ⵜⵉⵔⵔⵉⵏ', 'ⴰⴳⵓⵊⵊⵓ'], 1),
Question(9, 'ⴰⵏⵡⴰ ⵜⴰⴼⵔⵓⵜ ⵢⴻⵍⵍⴰ ⴷ-ⵎⵓⵔⴰⴷⴰ?', ['ⵎⴰⵏⴰⵍ', 'ⵓⵡⴰ', 'ⴱⵍⴰⵟⴰⵏ', 'ⵍⵉⵎⵓⵏ'], 1),
Question(10, 'ⴰⵏⵡⴰ ⴰⵣⵓⵍ?', ['ⵔⵓⵙⴰ', 'ⵔⵓⴽⴰ', 'ⵀⵉⵔⴱⴰ', 'ⴰⵖⵔⵓⵍ'], 0),
Question(11, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⴷ-ⵙⴰⴱⴰⵔ?', ['ⵜⵓⵔⵜⵓⴳⴰ', 'ⵔⴰⵏⴰ', 'ⴰⵏⵏⴰ', 'ⴱⴻⵣⴻⵍ'], 0),
Question(12, 'ⴰⵏⵡⴰ ⴰⵡⴰⵙⵙⴰ ⵢⴻⵍⵍⴰ ⵉⵎⵉⵍ?', ['ⵓⵎⵉⴷ', 'ⵎⵉⵍ', 'ⵀⴰⵔⵉⵏⴰ', 'ⵙⴰⵍ'], 1),
Question(13, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵏ ⵉⵏⵙⵜⵔⵓⵎⵏⵉ?', ['ⴱⵉⵍⵉⵏ', 'ⵣⴰⴱⵓⵜ', 'ⴱⴻⵍⵓ', 'ⴽⵓⴷⵓⵔⴰ'], 0),
Question(14, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⴷ-ⵙⴻⵙⴻⵏ ⴱⴰⵍⴰⵏⵙⵜⴰ?', ['ⴱⴰⵍⵓⵏ', 'ⴳⵓⴰⵏⵜ', 'ⵔⴰⵇⴻⵜⴰ', 'ⵔⴻⴷ'], 0),
Question(15, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⴷ-ⵣⴻⵙ ⵏ ⵢⵉⵍⵓⵜ?', ['ⵜⴰⴼⵓⴽⵜ', 'ⵣⴻⵙⵜⵔⴰⵙ', 'ⴰⴷⵔⴰⵔⵜ', 'ⴰⵎⵔⴰⵙ'], 1),
Question(16, 'ⴰⵏⵡⴰ ⴷⴰ ⵢⴻⵍⵍⴰ "ⵎⵓⵡⵡⵓ"?', ['ⴰⵎⴰⵏ', 'ⵖⵓⵏⴰ', 'ⴰⵏⵏⴰ', 'ⴱⴰⵟⵓ'], 0),
Question(17, 'ⴰⵏⵡⴰ ⴷⴰ ⵢⴻⵍⵍⴰ ⴷ-ⴰⵡⴰⵣⵣⴰ?', ['ⴱⵔⵓⴽⵍⵉ', 'ⴱⵍⴰⵟⴰⵏ', 'ⴼⵔⴻⵙⴰ', 'ⵎⵍⵓⵏ'], 0),
Question(18, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵙⴷⵎⴰⵏ ⵏ ⴰⵣⵣⴰⵍ?', ['ⴽⵓⵛ', 'ⴰⵡⴰⵏ', 'ⴱⵉⵙⵉⴽⵍⴰⵜ', 'ⴱⴰⵔⴽ'], 2),
Question(19, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵏ ⵉⵏⵙⴻⴷ ⴷ-ⵎⴰⵡⵔⴰⵙⴰ?', ['ⵎⴰⵔⵉⴱⵓⵙⴰ', 'ⵀⵓⵔⵎⵉⵜ', 'ⵎⵓⵙⴽⵓ', 'ⴰⴱⴻⵊⴰ'], 0),
Question(20, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵢⴻⴱⴻⵙ ⵎⴰⵍ ⴳⴰⵍⴻⵜⵓⵙ?', ['ⵉⵣⵓⵖ', 'ⵎⵉⵍ', 'ⴽⴰⴼⴻ', 'ⴰⵎⴰⵏ'], 1),
Question(21, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵢⴻⴱⴻⵙ ⵏ ⵏⵓⴱⴰⵙ?', ['ⵍⵍⵉⵢⴰ', 'ⴼⵓⵔ', 'ⵙⴰⵏⴷ', 'ⵜⴰⵔⵉⴷⵜ'], 0),
Question(22, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵢⴻⴱⴻⵙ ⵏ ⵓⴷⴷⵓⴷ ⴰⵏⵏⵓⵔ?', ['ⵣⴰⴱⵓⵙⴰⵎ', 'ⵔⴻⴳⴰⵍⵓ', 'ⵙⵉⵍⵍⴰ', 'ⵜⴰⵣⴰ'], 1),
Question(23, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⴷ-ⴰⵏⵉⵎⴰⵍ ⵢⴻⴱⴻⵙ ⴷⴰ ⵜⵓⴳⴰ ⴷⴰⵢⵢⵓⵔ?', ['ⵍⴻⵡⵓⵏ', 'ⵣⵓⵔⵣⵓ', 'ⴰⵍⴻⴼⴰⵏⵜ', 'ⴱⴰⵟⵓ'], 1),
Question(24, 'ⴰⵏⵡⴰ ⴷⴰ ⴰⵡⵍⴰⵏ ⵢⴻⵍⵍⴰ ⵏ ⵜⴰⵙⵔⴰⵙ?', ['ⵔⵓⵊⴰⵙ', 'ⴰⵣⵓⵍ', 'ⵖⵔⵓⵏⵏⵓ', 'ⵃⴰⵎⵔ'], 0),
Question(25, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⴷ-ⴰⵏⵉⵎⴰⵍ ⵢⴻⴱⴻⵙ ⴰⵙⴰⵏ?', ['ⴱⴰⵍⵓⵏⴰ', 'ⴱⴰⵢⵔⵓ', 'ⴰⵏⵏⴰ', 'ⴰⵍⴰⴷ'], 1),
Question(26, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⴷ-ⴰⵣⵣⴰⴹ ⵏ ⴰⵔⴰⵔ?', ['ⴱⵉⵣⵣⴰ', 'ⴱⴰⵏ', 'ⵉⵏⵙⴰⵍⴰⴷⴰ', 'ⴱⴰⵔⴰⵏ'], 1),
Question(27, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵢⴻⵙⵏⵓⴼⴹ ⴷ-ⵣⴻⵙ ⵏ ⵢⵉⵍⵓⵜ?', ['ⵏⵓⴱⴰⵙ', 'ⴰⵎⴰⵏ', 'ⴰⴷⵔⴰⵔ', 'ⴰⴹⵔⴰ'], 1),
Question(28, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵢⴻⴱⴻⵙ ⵏ ⵓⴷⴷⵓⴷ?', ['ⵉⵙⵙⴰⵏ', 'ⵓⵙⵙⴰ ⵏ ⴰⵙⵏ', 'ⴱⴰⵔⴽ', 'ⵍⴰⴱⵉⵣ'], 1),
Question(29, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵢⴻⴱⴻⵙ ⵏ ⵉⵎⵓⵍ?', ['ⴱⴻⵣ', 'ⴳⴰⵜ', 'ⴰⵏⵏⴰ', 'ⵍⴻⵡⵓⵏ'], 0),
Question(30, 'ⴰⵏⵡⴰ ⵢⴻⵍⵍⴰ ⵢⴻⴱⴻⵙ ⵏ ⴰⵎⴰⵙ?', ['10', '12', '11', '13'], 1),
],





};
