// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnBGkChkJR9GHLdzrMlQBN8J2X-uJkmqY',
    appId: '1:1083672847922:web:7002362566ed62b205be2b',
    messagingSenderId: '1083672847922',
    projectId: 'moortaalim-58b73',
    authDomain: 'moortaalim-58b73.firebaseapp.com',
    storageBucket: 'moortaalim-58b73.firebasestorage.app',
    measurementId: 'G-S6T487M8SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMmcn9StYu22k_kPPBxyVG7SqQD9PYPtA',
    appId: '1:1083672847922:android:eef60daf141168ce05be2b',
    messagingSenderId: '1083672847922',
    projectId: 'moortaalim-58b73',
    storageBucket: 'moortaalim-58b73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoIINI4qOhIWLgw2JECuplopTn9BWkPx8',
    appId: '1:1083672847922:ios:9465e50e3021204205be2b',
    messagingSenderId: '1083672847922',
    projectId: 'moortaalim-58b73',
    storageBucket: 'moortaalim-58b73.firebasestorage.app',
    iosBundleId: 'com.jalnix.moortaalim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoIINI4qOhIWLgw2JECuplopTn9BWkPx8',
    appId: '1:1083672847922:ios:9465e50e3021204205be2b',
    messagingSenderId: '1083672847922',
    projectId: 'moortaalim-58b73',
    storageBucket: 'moortaalim-58b73.firebasestorage.app',
    iosBundleId: 'com.jalnix.moortaalim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnBGkChkJR9GHLdzrMlQBN8J2X-uJkmqY',
    appId: '1:1083672847922:web:ddb4f312c0dabc6a05be2b',
    messagingSenderId: '1083672847922',
    projectId: 'moortaalim-58b73',
    authDomain: 'moortaalim-58b73.firebaseapp.com',
    storageBucket: 'moortaalim-58b73.firebasestorage.app',
    measurementId: 'G-KVQFEFVR2N',
  );
}
