import 'package:flutter/material.dart';

final List<Map<String, dynamic>> games = [
  {
    'title': 'drawingAlphabet',
    'icon': Icons.brush,
    'routeName': 'DrawingAlphabet',
    'color': Colors.deepPurple,
    'locked': false,
    'cost': 0,
    'unlockType': 'creative',
  },
  {
    'title': 'quizGame',
    'icon': Icons.quiz,
    'routeName': 'QuizGameApp',
    'color': Colors.deepOrange,
    'locked': true,
    'cost': 10,
    'unlockType': 'logic',
  },
  {
    'title': 'appStories',
    'icon': Icons.menu_book,
    'routeName': 'AppStories',
    'color': Colors.blue,
    'locked': true,
    'cost': 15,
    'unlockType': 'reading',
  },
  {
    'title': 'shapeSorter',
    'icon': Icons.square_foot_outlined,
    'routeName': 'ShapeSorter',
    'color': Colors.green,
    'locked': true,
    'cost': 15,
    'unlockType': 'puzzle',
  },
  {
    'title': 'PlaneDestroyer',
    'icon': Icons.dashboard_outlined,
    'routeName': 'PlaneDestroyer',
    'color': Colors.teal,
    'locked': false,
    'cost': 15,
    'unlockType': 'strategy',
  },
  {
    'title': 'piano',
    'icon': Icons.piano,
    'routeName': 'Piano',
    'color': Colors.black,
    'locked': true,
    'cost': 15,
    'unlockType': 'music',
  },
  {
    'title': 'WordLink',
    'icon': Icons.sort_by_alpha_outlined,
    'routeName': 'WordLink',
    'color': Colors.indigo,
    'locked': true,
    'cost': 10,
    'unlockType': 'language',
  },
  {
    'title': 'IQGame',
    'icon': Icons.smart_toy_outlined,
    'routeName': 'IQGame',
    'color': Colors.pinkAccent,
    'locked': true,
    'cost': 10,
    'unlockType': 'iq',
  },

  {
    'title': 'JumpingBoard',
    'icon': Icons.attractions,
    'routeName': 'JumpingBoard',
    'color': Colors.green,
    'locked': true,
    'cost': 10,
    'unlockType': 'iq',
  },

  {
    'title': 'MagicPainting',
    'icon': Icons.format_paint,
    'routeName': 'MagicPainting',
    'color': Colors.orange,
    'locked': true,
    'cost': 50,
    'unlockType': 'iq',
  },


];
