class AllAssets {
  static const List<String> allAvatars = [

    //AvatrIImage Aliens
    'assets/images/AvatarImage/Aliens/Alien1.png',
    'assets/images/AvatarImage/Aliens/Alien2.png',
    'assets/images/AvatarImage/Aliens/Alien3.png',
    'assets/images/AvatarImage/Aliens/Alien4.png',
    'assets/images/AvatarImage/Aliens/Alien5.png',
    'assets/images/AvatarImage/Aliens/Alien6.png',
    'assets/images/AvatarImage/Aliens/Alien7.png',
    'assets/images/AvatarImage/Aliens/Alien8.png',
    'assets/images/AvatarImage/Aliens/Alien9.png',
    'assets/images/AvatarImage/Aliens/Alien10.png',
    'assets/images/AvatarImage/Aliens/Alien11.png',
    'assets/images/AvatarImage/Aliens/Alien12.png',
    'assets/images/AvatarImage/Aliens/Alien13.png',
    'assets/images/AvatarImage/Aliens/Alien14.png',
    'assets/images/AvatarImage/Aliens/Alien15.png',
    'assets/images/AvatarImage/Aliens/Alien16.png',
    'assets/images/AvatarImage/Aliens/Alien17.png',
    'assets/images/AvatarImage/Aliens/Alien18.png',
    'assets/images/AvatarImage/Aliens/Alien19.png',
    'assets/images/AvatarImage/Aliens/Alien20.png',
    'assets/images/AvatarImage/Aliens/Alien21.png',
    'assets/images/AvatarImage/Aliens/Alien22.png',
    'assets/images/AvatarImage/Aliens/Alien23.png',
    'assets/images/AvatarImage/Aliens/Alien24.png',
    'assets/images/AvatarImage/Aliens/Alien25.png',
    'assets/images/AvatarImage/Aliens/Alien26.png',
    'assets/images/AvatarImage/Aliens/Alien27.png',
    'assets/images/AvatarImage/Aliens/Alien28.png',
    'assets/images/AvatarImage/Aliens/Alien29.png',
    'assets/images/AvatarImage/Aliens/Alien30.png',
    'assets/images/AvatarImage/Aliens/Alien31.png',
    'assets/images/AvatarImage/Aliens/Alien32.png',
    'assets/images/AvatarImage/Aliens/Alien33.png',

    //

    'assets/images/AvatarImage/Babies/baby1.png',
    'assets/images/AvatarImage/Babies/baby2.png',
    'assets/images/AvatarImage/Babies/baby3.png',
    'assets/images/AvatarImage/Babies/baby4.png',
    'assets/images/AvatarImage/Babies/baby5.png',
    'assets/images/AvatarImage/Babies/baby6.png',
    'assets/images/AvatarImage/Babies/baby7.png',
    'assets/images/AvatarImage/Babies/baby8.png',
    'assets/images/AvatarImage/Babies/baby9.png',
    'assets/images/AvatarImage/Babies/baby10.png',
    'assets/images/AvatarImage/Babies/baby11.png',
    'assets/images/AvatarImage/Babies/baby12.png',
    'assets/images/AvatarImage/Babies/baby13.png',
    'assets/images/AvatarImage/Babies/baby14.png',
    'assets/images/AvatarImage/Babies/baby15.png',
    'assets/images/AvatarImage/Babies/baby16.png',
    'assets/images/AvatarImage/Babies/baby17.png',
    'assets/images/AvatarImage/Babies/baby18.png',
    'assets/images/AvatarImage/Babies/baby19.png',
    'assets/images/AvatarImage/Babies/baby20.png',
    'assets/images/AvatarImage/Babies/baby21.png',
    'assets/images/AvatarImage/Babies/baby22.png',
    'assets/images/AvatarImage/Babies/baby23.png',
    'assets/images/AvatarImage/Beams/Beam1.jpg',
    'assets/images/AvatarImage/Beams/Beam2.jpg',
    'assets/images/AvatarImage/Beams/Beam3.jpg',
    'assets/images/AvatarImage/Beams/Beam4.jpg',
    'assets/images/AvatarImage/Beams/Beam5.jpg',
    'assets/images/AvatarImage/Beams/Beam6.jpg',
    'assets/images/AvatarImage/Beams/Beam7.jpg',
    'assets/images/AvatarImage/Beams/Beam8.jpg',
    'assets/images/AvatarImage/Beams/Beam9.jpg',
    'assets/images/AvatarImage/Beams/Beam10.jpg',
    'assets/images/AvatarImage/Beams/Beam11.jpg',
    'assets/images/AvatarImage/Beams/Beam12.jpg',
    'assets/images/AvatarImage/Beams/Beam13.jpg',
    'assets/images/AvatarImage/Beams/Beam14.jpg',
    'assets/images/AvatarImage/Beams/Beam15.jpg',
    'assets/images/AvatarImage/Beams/Beam16.jpg',
    'assets/images/AvatarImage/Beams/Beam17.jpg',
    'assets/images/AvatarImage/Beams/Beam18.jpg',
    'assets/images/AvatarImage/Beams/Beam19.jpg',
    'assets/images/AvatarImage/Beams/Beam20.jpg',
    'assets/images/AvatarImage/Beams/Beam21.jpg',
    'assets/images/AvatarImage/Beams/Beam22.jpg',
    'assets/images/AvatarImage/Beams/Beam23.jpg',
    'assets/images/AvatarImage/Beams/Beam24.jpg',
    'assets/images/AvatarImage/Beams/Beam25.jpg',
    'assets/images/AvatarImage/Beams/Beam26.jpg',
    'assets/images/AvatarImage/Beams/Beam27.jpg',
    'assets/images/AvatarImage/Beams/Beam28.jpg',


    // add all avatar paths here
  ];

  static const List<String> allBanners = [
        'assets/images/Banners/CuteBr/Banner1.png',
        'assets/images/Banners/CuteBr/Banner2.png',
        'assets/images/Banners/CuteBr/Banner3.png',
        'assets/images/Banners/CuteBr/Banner4.png',
        'assets/images/Banners/CuteBr/Banner5.png',
        'assets/images/Banners/CuteBr/Banner6.png',
        'assets/images/Banners/CuteBr/Banner7.png',
        'assets/images/Banners/CuteBr/Banner8.png',
        'assets/images/Banners/CuteBr/Banner9.png',
        'assets/images/Banners/CuteBr/Banner10.png',
        'assets/images/Banners/CuteBr/Banner11.png',
        'assets/images/Banners/CuteBr/Banner12.png',
        'assets/images/Banners/CuteBr/Banner13.png',
        'assets/images/Banners/CuteBr/Banner14.png',
        'assets/images/Banners/CuteBr/Banner15.png',
        'assets/images/Banners/CuteBr/Banner16.png',
        'assets/images/Banners/CuteBr/Banner17.png',
        'assets/images/Banners/CuteBr/Joyful1.png',
        'assets/images/Banners/CuteBr/Joyful2.png',
        'assets/images/Banners/CuteBr/Joyful3.png',
        'assets/images/Banners/CuteBr/Joyful4.png',
        'assets/images/Banners/CuteBr/Joyful5.png',
        'assets/images/Banners/CuteBr/Joyful6.png',
        'assets/images/Banners/CuteBr/Joyful7.png',
        'assets/images/Banners/CuteBr/Joyful8.png',
        'assets/images/Banners/CuteBr/Joyful9.png',
        'assets/images/Banners/CuteBr/Joyful10.png',
        'assets/images/Banners/CuteBr/Joyful11.png',
        'assets/images/Banners/CuteBr/Joyful12.png',

  ];

  static const List<String> allLotties = [
    'assets/animations/AnimatedAvatars/CatCrying.json',
    'assets/animations/AnimatedAvatars/CatLove.json',
    'assets/animations/AnimatedAvatars/CuteBearDancing.json',
    'assets/animations/AnimatedAvatars/CuteDogEat.json',
    'assets/animations/AnimatedAvatars/RabbitWithBall.json',
    'assets/animations/AnimatedAvatars/Smoothymon_typing.json',
    // add all lottie paths here
  ];
}
